apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upbit-backend-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upbit-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # CPU 60% 넘으면 스케일 아웃
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upbit-frontend-hpa
  namespace: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upbit-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # CPU 60% 넘으면 스케일 아웃
