# 1. 프론트엔드 연결 (Namespace: frontend)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upbit-frontend-ingress
  namespace: frontend
  annotations:
    # SPA(리액트 등) 라우팅 문제를 위해 메인으로 리다이렉트
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: upbit.local # 사용할 도메인
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: upbit-frontend # 서비스 이름 확인
                port:
                  number: 80 # 프론트엔드 서비스 포트

---
# 2. 백엔드 연결 (Namespace: backend)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upbit-backend-ingress
  namespace: backend
  annotations:
    # /api/users 로 들어오면 백엔드에는 /users 로 전달 (필요 시 주석 해제)
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: upbit.local
      http:
        paths:
          - path: /api # /api 로 시작하는 요청은 백엔드로
            pathType: Prefix
            backend:
              service:
                name: upbit-backend # 서비스 이름 확인
                port:
                  number: 3000 # 백엔드 서비스 포트 (아까 3000으로 통일함)
