apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-area-1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.184.203-192.168.184.212
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-1
  namespace: metallb-system
