apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: database
data:
  redis-password: MDMyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: timescale-secret
  namespace: database
data:
  pg-user-id: bGVl # lee
  pg-user-password: MDMyMw== # 0323
  pg-root-password: MDMyMw== # 0323
  pg-db-name: dXBiaXQ= # upbit
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
  labels:
    app: upbit-backend
stringData:
  DB_USER: "app"
  DB_PASSWORD: "0323"
  DATABASE_URL: "postgresql://app:0323@timescaledb-rw.database.svc.cluster.local:5432/app?schema=public&connect_timeout=30"
  JWT_SECRET_KEY: "0323"
  REDIS_PASSWORD: "0323"
