apiVersion: v1
kind: Secret
metadata:
  name: upbit-secrets
  namespace: upbit
  labels:
    app.kubernetes.io/name: upbit
type: Opaque
stringData:
  # Database credentials
  DB_USER: "postgres"
  DB_PASSWORD: "0323"

  # JWT secret
  JWT_SECRET_KEY: "0323"

  # Full database URL (for Prisma)
  DATABASE_URL: "postgresql://postgres:0323@db-master-0.db-headless.database.svc.cluster.local:5432/upbit"
